import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/shared/navigation/nav"

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: { template: "% / VillaLink", default: "Bienvenido /" },
  description: "Generated by Aracely",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-gray-50 font-sans`}>
        {/* Header */}
        <Header/>
        {/* Main Content */}
        <main className="p-6 space-y-12">
          {children}
        </main>
 
        {/* Footer */}
        <footer className="bg-gray-900 text-white text-center p-6">
          <p>Universidad Nacional Federico Villarreal</p>
          <p>Dirección y otros datos de contacto aquí</p>
        </footer>
      </body>
    </html>
  );
}
